<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Javiera Rojas">

<title>Impacto integral de inmigrantes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Impacto_integral_inmigrantes_files/libs/clipboard/clipboard.min.js"></script>
<script src="Impacto_integral_inmigrantes_files/libs/quarto-html/quarto.js"></script>
<script src="Impacto_integral_inmigrantes_files/libs/quarto-html/popper.min.js"></script>
<script src="Impacto_integral_inmigrantes_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Impacto_integral_inmigrantes_files/libs/quarto-html/anchor.min.js"></script>
<link href="Impacto_integral_inmigrantes_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Impacto_integral_inmigrantes_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Impacto_integral_inmigrantes_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Impacto_integral_inmigrantes_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Impacto_integral_inmigrantes_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Impacto integral de inmigrantes</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Javiera Rojas </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="percepción-y-actitudes-de-la-población-chilena-hacia-la-migración-un-análisis-de-variables-multidimensionales" class="level2">
<h2 class="anchored" data-anchor-id="percepción-y-actitudes-de-la-población-chilena-hacia-la-migración-un-análisis-de-variables-multidimensionales">Percepción y Actitudes de la Población Chilena hacia la Migración: Un Análisis de Variables Multidimensionales</h2>
<p>El fenómeno de la migración ha cobrado una creciente relevancia en Chile en las últimas décadas, generando debates y discusiones en torno a su impacto en la sociedad. La diversidad social a nivel socio-cultural, politica y economicamente llega afectar a una sociedad determinada, sobre todo genera complicaciones y conflictos sociales a la hora de interactuar e intregrarse socialmente, ya sea a nivel individual, intersubjetivo o social; estos comportamientos afectarían directamente a la cohesión y/o segregación social. Analizar la manera de pensar de la población chilena respecto a una sociedad diversa y multicultural, incluyendo posibles prejuicios o estereotipos.</p>
<p>Este estudio se propone a explorar las percepciones y actitudes de la población chilena hacía la migración, utilizando los datos abtraidos de la base de datos “Latinobarometro, cuestionario 2023”, la cual maneja e investiga el desarrollo de la democracia, la economía y la sociedad en su conjunto, por medio de un estudio de opinión pública que aplica anualmente alrededor de 18 países de América Latina representando a más de 600 millones de habitantes; producen y publican los resultados, permitiendo ser utilizados en estudios como este. Para este estudio utilizamos diversas dimensiones para lograr explorar las distintas formas de pensar y grado de acuerdo respecto una sociedad mas diversa, afectado por la llegada de inmigrantes al país; entre ellos contamos con: Grado de acuerdo: Los inmigrantes son buenos para la economia del país, Grado de acuerdo: Inmigrantes causan un aumento del crimen, Grado de acuerdo: Los inmigrantes mejoran nuestra sociedad con ideas y cultura, finalmente la manera de pensar sobre una sociedad mas diversa o una que mantenga una defensa en sus tradicicones y costumbres. Para fines de esta ivestigación se trabajó con una base de datos recodificada, incorporando estas variables y fltrada a caso chileno.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 0.Ajustes iniciales:</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">999</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># PAQUETES</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pacman)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(haven,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>               sjlabelled,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>               dplyr, <span class="co">#Manipulacion de datos</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>               stargazer, <span class="co">#Tablas</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>               sjmisc, <span class="co"># Tablas</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>               summarytools, <span class="co"># Tablas</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>               kableExtra, <span class="co">#Tablas</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>               sjPlot, <span class="co">#Tablas y gráficos</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>               corrplot, <span class="co"># Correlaciones</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>               sessioninfo, <span class="co"># Información de la sesión de trabajo</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>               ggplot2,  <span class="co"># Para la mayoría de los gráficos</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>               mice)   <span class="co">#Para imputar NA's</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Installing package into 'C:/Users/Javi/AppData/Local/R/win-library/4.2'
(as 'lib' is unspecified)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/4.2:
  no fue posible abrir la URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/4.2/PACKAGES'</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>package 'sjPlot' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
    C:\Users\Javi\AppData\Local\Temp\Rtmp2R35R1\downloaded_packages</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
sjPlot installed</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in pacman::p_load(haven, sjlabelled, dplyr, stargazer, sjmisc, summarytools, : Failed to install/load:
sjPlot</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#2.Carga de base:</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="at">file =</span> <span class="st">"Input/proc_data.RData"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#3.Descriptivos:</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>summarytools<span class="sc">::</span><span class="fu">dfSummary</span>(proc_data, <span class="at">plain.ascii =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>### Data Frame Summary  
#### proc_data  
**Dimensions:** 1077 x 6  
**Duplicates:** 912  

---------------------------------------------------------------------------------------------------------------
No   Variable        Stats / Values           Freqs (% of Valid)    Graph                  Valid      Missing  
---- --------------- ------------------------ --------------------- ---------------------- ---------- ---------
1    idenpa\         1 distinct value         152 : 1077 (100.0%)   IIIIIIIIIIIIIIIIIIII   1077\      0\       
     [integer]                                                                             (100.0%)   (0.0%)   

2    soc_diversa\    Min  : 1\                1 : 594 (55.2%)\      IIIIIIIIIII \          1077\      0\       
     [integer]       Mean : 1.4\              2 : 483 (44.8%)       IIIIIIII               (100.0%)   (0.0%)   
                     Max  : 2                                                                                  

3    inmi_llega\     Mean (sd) : 2.2 (0.6)\   1 : 124 (11.5%)\      II \                   1077\      0\       
     [integer]       min &lt; med &lt; max:\        2 : 661 (61.4%)\      IIIIIIIIIIII \         (100.0%)   (0.0%)   
                     1 &lt; 2 &lt; 3\               3 : 292 (27.1%)       IIIII                                      
                     IQR (CV) : 1 (0.3)                                                                        

4    inmi_ideycul\   Mean (sd) : 2.8 (0.9)\   1 :  62 ( 5.8%)\      I \                    1077\      0\       
     [integer]       min &lt; med &lt; max:\        2 : 375 (34.8%)\      IIIIII \               (100.0%)   (0.0%)   
                     1 &lt; 3 &lt; 4\               3 : 392 (36.4%)\      IIIIIII \                                  
                     IQR (CV) : 1 (0.3)       4 : 248 (23.0%)       IIII                                       

5    inmi_crim\      Mean (sd) : 1.7 (0.7)\   1 : 438 (40.7%)\      IIIIIIII \             1077\      0\       
     [integer]       min &lt; med &lt; max:\        2 : 508 (47.2%)\      IIIIIIIII \            (100.0%)   (0.0%)   
                     1 &lt; 2 &lt; 4\               3 : 106 ( 9.8%)\      I \                                        
                     IQR (CV) : 1 (0.4)       4 :  25 ( 2.3%)                                                  

6    inmi_eco\       Mean (sd) : 2.9 (0.8)\   1 :  49 ( 4.5%)\      \                      1077\      0\       
     [integer]       min &lt; med &lt; max:\        2 : 280 (26.0%)\      IIIII \                (100.0%)   (0.0%)   
                     1 &lt; 3 &lt; 4\               3 : 509 (47.3%)\      IIIIIIIII \                                
                     IQR (CV) : 1 (0.3)       4 : 239 (22.2%)       IIII                                       
---------------------------------------------------------------------------------------------------------------</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(<span class="fu">dfSummary</span>(proc_data, <span class="at">headings=</span><span class="cn">FALSE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable</span>(.,<span class="st">"markdown"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Switching method to 'browser'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Output file written: C:\Users\Javi\AppData\Local\Temp\Rtmp2R35R1\filef841e54372.html</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Switching method to 'browser'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Output file written: C:\Users\Javi\AppData\Local\Temp\Rtmp2R35R1\filef847e2c4af4.html</code></pre>
</div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">C:2R35R1847e2c4af4.html</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La tabla nos muestra como en general parece haber una tendencia hacía actitudes positivas o neutrales hacía la inmigración en diferentes aspectos evaluados, como la llegada de inmigrantes, teniendo en claro que esta puede perjudicar o beneficiar a la sociedad; el aporte de ideas y cultura, seguido por la forma de pensar respecto a que esta sea mas diversa, y su impacto económico. Sin embargo, la percepción en relación con el crimen parece ser más variada.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#3.1 Gráficos:</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>inmi_ideycul)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;integer&gt; 
# total N=1077 valid N=1077 mean=2.77 sd=0.87

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 |  62 |  5.76 |    5.76 |   5.76
    2 | 375 | 34.82 |   34.82 |  40.58
    3 | 392 | 36.40 |   36.40 |  76.97
    4 | 248 | 23.03 |   23.03 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(proc_data, <span class="fu">aes</span>(<span class="at">x =</span> inmi_ideycul)) <span class="sc">+</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"pink"</span>) <span class="sc">+</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span> (<span class="at">title =</span> <span class="st">"Interculturalidad"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Impacto_integral_inmigrantes_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>inmi_crim)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;integer&gt; 
# total N=1077 valid N=1077 mean=1.74 sd=0.73

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 | 438 | 40.67 |   40.67 |  40.67
    2 | 508 | 47.17 |   47.17 |  87.84
    3 | 106 |  9.84 |    9.84 |  97.68
    4 |  25 |  2.32 |    2.32 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(proc_data, <span class="fu">aes</span>(<span class="at">x =</span> inmi_crim)) <span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"pink"</span>) <span class="sc">+</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span> (<span class="at">title =</span> <span class="st">"Aumento inmigración-crimen"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Impacto_integral_inmigrantes_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>inmi_eco)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;integer&gt; 
# total N=1077 valid N=1077 mean=2.87 sd=0.80

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 |  49 |  4.55 |    4.55 |   4.55
    2 | 280 | 26.00 |   26.00 |  30.55
    3 | 509 | 47.26 |   47.26 |  77.81
    4 | 239 | 22.19 |   22.19 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(proc_data, <span class="fu">aes</span>(<span class="at">x =</span> inmi_eco)) <span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"pink"</span>) <span class="sc">+</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span> (<span class="at">title =</span> <span class="st">"Impacto económico de los inmigrantes"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Impacto_integral_inmigrantes_files/figure-html/unnamed-chunk-5-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Si observamos el grafico “Interculturalidad” nos entrega informacion respecto al grado de acuerdo de la poblacion Chilena al considerar que los inmigrantes han logrado mejorar nuestra sociedad con ideas y cutura; más de 350 personas están de acuerdo, sin embargo, cerca de 400 personas mantienen su desacuerdo. Se interpreta una fuerte opinion a la idea de que la sociedad Chilena defiende sus costumbres.</p>
<p>Si bien el grafico “Aumento inmigracion-crimen”, referida a que han aumentado la delincuencia en las calles. Si bien tiene dos de sus barras muy cercanas, observamos que mas de 500 personas estarian de acuerdo en que gracias al fenomeno de la migración, se ha visualizado un aumento en el crimen. Muy pocas personas, menos de 100, estarian en contra de esto.</p>
<p>Por ultimo, si analizamos brevemente el ultimo grafico “impacto economico de los inmigrantes”, entendiendo este impacto a partir de si los inmigrantes son buenos para la economia del país. La mayoria de la sociedad Chilena estaría en desacuerdo con este postulado. Se podría deber a dististos factores que llegan a afectar la manera de pensar, socialmente el pensamiendo de “nos vienen a robar el trabajo” está normalizado.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#4.Correlación:</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>cor_proc_data <span class="ot">&lt;-</span> <span class="fu">cor</span>(proc_data,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor(proc_data, use = "complete.obs"): the standard deviation is zero</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>cor_proc_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             idenpa soc_diversa  inmi_llega inmi_ideycul  inmi_crim   inmi_eco
idenpa            1          NA          NA           NA         NA         NA
soc_diversa      NA  1.00000000 -0.04450943   -0.3555942  0.2218694 -0.2892966
inmi_llega       NA -0.04450943  1.00000000    0.0731263 -0.1103265  0.1375182
inmi_ideycul     NA -0.35559423  0.07312630    1.0000000 -0.3757125  0.5934392
inmi_crim        NA  0.22186937 -0.11032652   -0.3757125  1.0000000 -0.4384266
inmi_eco         NA -0.28929657  0.13751819    0.5934392 -0.4384266  1.0000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot.mixed</span>(cor_proc_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Impacto_integral_inmigrantes_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Hay correlaciones calculadas entre “soc_diversa” referida a la manera de pensar que tiene la poblacion Chilena respecto a una sociedad la cual defienda sus costumbres o una que éste abierta a la diveridad de todo tipo de costumbres, e “inmi_ideycul” entendida como aportacion positiva de inmigrantes a la sociedad en idea y cultura, esta es de -0.35559423, lo que sugiere una correlación negativa moderada. Esto significa que hay una asociación inversa entre la percepción de la diversidad social y la percepción de la interculturalidad. Hay una correlación positiva moderada entre “inmi_llega” : llegada de inmigrantes perjudica o beneficia, e “inmi_eco”: imigrantes aportan positivamete ala economia del país, es de (0.13751819), lo que sugiere que una percepción positiva de la llegada de inmigrantes tiende a estar asociada con una percepción positiva del impacto económico de la inmigración.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#5.Confiabilidad del conjunto:</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Alpha de Cronbach:</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">alpha</span>(proc_data, <span class="at">check.keys =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in psych::alpha(proc_data, check.keys = TRUE): Item = idenpa had no
variance and was deleted but still is counted in the score</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in psych::alpha(proc_data, check.keys = TRUE): Some items were negatively correlated with the first principal component and were automatically reversed.
 This is indicated by a negative sign for the variable name.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = proc_data, check.keys = TRUE)

  raw_alpha std.alpha G6(smc) average_r   S/N   ase mean   sd median_r
      0.66     -0.38  0.0062    -0.059 -0.28 0.015   28 0.39   -0.077

    95% confidence boundaries 
         lower alpha upper
Feldt     0.63  0.66  0.69
Duhachek  0.63  0.66  0.69

 Reliability if an item is dropped:
             raw_alpha std.alpha G6(smc) average_r    S/N alpha se var.r  med.r
soc_diversa-      0.64    -0.085   0.207    -0.020 -0.079    0.017 0.144 -0.019
inmi_llega        0.71    -0.633  -0.044    -0.107 -0.388    0.013 0.175 -0.322
inmi_ideycul      0.53    -0.472  -0.165    -0.087 -0.321    0.022 0.063 -0.077
inmi_crim-        0.59     0.072   0.270     0.019  0.078    0.018 0.117  0.014
inmi_eco          0.50    -0.559  -0.233    -0.099 -0.359    0.023 0.056 -0.077

 Item statistics 
                n raw.r std.r r.cor r.drop mean   sd
soc_diversa- 1077  0.53  0.27 -2.13   0.35  3.6 0.50
inmi_llega   1077  0.38  0.54  0.51   0.13  2.2 0.60
inmi_ideycul 1077  0.79  0.48  2.19   0.57  2.8 0.87
inmi_crim-   1077  0.68  0.15 -3.14   0.45  3.3 0.73
inmi_eco     1077  0.80  0.51  2.72   0.61  2.9 0.80

Non missing response frequency for each item
                1    2    3    4 miss
soc_diversa  0.55 0.45 0.00 0.00    0
inmi_llega   0.12 0.61 0.27 0.00    0
inmi_ideycul 0.06 0.35 0.36 0.23    0
inmi_crim    0.41 0.47 0.10 0.02    0
inmi_eco     0.05 0.26 0.47 0.22    0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Alpha de Cronbach recodificado:</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">alpha</span>(dplyr<span class="sc">::</span><span class="fu">select</span>(proc_data, inmi_ideycul, inmi_crim, inmi_eco),<span class="at">check.keys =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in psych::alpha(dplyr::select(proc_data, inmi_ideycul, inmi_crim, : Some items were negatively correlated with the first principal component and were automatically reversed.
 This is indicated by a negative sign for the variable name.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = dplyr::select(proc_data, inmi_ideycul, inmi_crim, 
    inmi_eco), check.keys = TRUE)

  raw_alpha std.alpha G6(smc) average_r   S/N   ase mean   sd median_r
      0.73     -0.26    0.21    -0.074 -0.21 0.014    3 0.65    -0.38

    95% confidence boundaries 
         lower alpha upper
Feldt      0.7  0.73  0.75
Duhachek   0.7  0.73  0.76

 Reliability if an item is dropped:
             raw_alpha std.alpha G6(smc) average_r   S/N alpha se var.r med.r
inmi_ideycul      0.61     -1.56   -0.44     -0.44 -0.61    0.024    NA -0.44
inmi_crim-        0.74      0.74    0.59      0.59  2.92    0.016    NA  0.59
inmi_eco          0.54     -1.20   -0.38     -0.38 -0.55    0.028    NA -0.38

 Item statistics 
                n raw.r std.r r.cor r.drop mean   sd
inmi_ideycul 1077  0.84  0.76  0.79   0.58  2.8 0.87
inmi_crim-   1077  0.73  0.12 -0.81   0.45  3.3 0.73
inmi_eco     1077  0.85  0.72  0.76   0.63  2.9 0.80

Non missing response frequency for each item
                1    2    3    4 miss
inmi_ideycul 0.06 0.35 0.36 0.23    0
inmi_crim    0.41 0.47 0.10 0.02    0
inmi_eco     0.05 0.26 0.47 0.22    0</code></pre>
</div>
</div>
<p>Este análisis indica que la consistencia entre las variables “inmi_ideycul”. “inmi_crim”, “inmi_eco” es aceptable y logran explicar la con mayor fiabilidad la percepción y actitudes de la población chilena respecto al fenomeno de migración, esta es de 0.73.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#CONSTRUCCION DE ESCALA:</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percepcion_impacto_integral_inmigrantes =</span> <span class="fu">sum</span>(inmi_ideycul, inmi_crim, inmi_eco))</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(proc_data<span class="sc">$</span>percepcion_impacto_integral_inmigrantes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  3.000   6.000   7.000   7.376   8.000  12.000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(proc_data, <span class="fu">aes</span>(<span class="at">x =</span> percepcion_impacto_integral_inmigrantes)) <span class="sc">+</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.6</span>, <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"yellow"</span>) <span class="sc">+</span>  </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Percepcion del impacto integral de inmigrantes"</span>) <span class="sc">+</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Frecuencia"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Impacto_integral_inmigrantes_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Esta escala ofrece una visión general de como está distribuida la “Percepcion del impacto integral de inmigrantes”, si bien tiene variabilidad en los extremos de la distribuicion, esta tiene centralidad alrededor de 7 en una escala de 3 a 12.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>